baseurl = "rebelfencing.github.io/rebelfencing"
title = "Rebel Fencing"
theme = "universal"
languageCode = "pl"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "pl"

# number of words of summarized post content (default 70)
summaryLength = 70

# not pluralize title pages by default
pluralizelisttitles = false

[services]
    # Enable Google Analytics by entering your tracking code
    [services.googleAnalytics]
        id = ""

# Define the number of posts per page
[pagination]
    pagerSize = 10

# Main menu
[menu]
[[menu.main]]
    name       = "Start"
    identifier = "menu.home"
    url        = "/"
    weight     = 1

[[menu.main]]
    name       = "O nas"
    url        = "/o-nas/"
    weight     = 2

[[menu.main]]
    name       = "Szermierka klasyczna"
    url        = "/szermierka-klasyczna/"
    weight     = 3

[[menu.main]]
    name       = "Treningi"
    url        = "/treningi/"
    weight     = 4

[[menu.main]]
    name       = "Wydarzenia"
    url        = "/wydarzenia/"
    weight     = 5


# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "Telefon"
    url = "tel:+48 600 358 163"
    pre = "<i class='fas fa-2x fa-phone'></i>"

[[menu.topbar]]
    weight = 2
    name = "GitHub"
    url = "https://github.com/devcows/hugo-universal-theme"
    pre = "<i class='fab fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 3
    name = "Facebook"
    url = "https://www.facebook.com/p/Rebel-Fencing-Szko%C5%82a-Szermierki-Klasycznej-100047775885738/"
    pre = "<i class='fab fa-2x fa-facebook'></i>"

[[menu.topbar]]
    weight = 4
    name = "Email"
    url = "mailto:info@rebelfencing.pl"
    pre = "<i class='fas fa-2x fa-envelope'></i>"

[params]
    author = "Rebel Fencing"
    defaultKeywords = ["szermierka klasyczna", "Wrocław", "Rebel Fencing"]
    mainSections = []
    defaultDescription = "Rebel Fencing – szkoła szermierki klasycznej we Wrocławiu"

    # Social media
    facebook_site = "https://www.facebook.com/p/Rebel-Fencing-Szko%C5%82a-Szermierki-Klasycznej-100047775885738/" # the Facebook handle of your site ('https://www.facebook.com/HANDLE')
    default_sharing_image = "img/rebel-logo-small.jpg"

    # Google Maps widget: If `googleMapsApiKey` is not set, no key will be passed to Google (which likely results in a broken map widget).
    enableGoogleMaps = false

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "default"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 50 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - register your account to https://formspree.io/register
    # - login and create new form
    # - set your form's endpoint url under 'formspree_action' below
    # - upload the generated site to your server
    # - test a dummy email yourself
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io endpoint url
    formspree_action = "https://formspree.io/sample/of/endpoint"
    contact_form_ajax = false

    # Formspree form supports Google reCAPTCHA Key (type v2).
    # If you use this feature, you should enable reCAPTCHA feature in the Formspree dashboard.
    #
    # By default, Formspree use a redirect page for recaptcha widget.
    # If you use a recaptcha widget in your contact page, you should do next steps.
    # (if you don't want, skip these steps)
    #
    #   1. register your site on Google recaptcha admin page: https://www.google.com/recaptcha/admin
    #   2. select reCAPTCHA v2 and checkbox widget type.
    #   3. remember site key and secret key.
    #   4. enter secret key into "Custom reCAPTCHA Key" field in your Formspree form setting page.
    #   5. change `enableRecaptchaInContactForm` is to true
    #   6. enter site key into `googleRecaptchaKey` to enable a recaptcha widget in your page.
    #
    enableRecaptchaInContactForm = false
    googleRecaptchaKey = "site_key_for_google_recaptcha"

    about_us = "<p>Rebel Fencing – szkoła szermierki klasycznej.</p>"
    copyright = "© Rebel Fencing"

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    dropdown_mouse_over = true

    disabled_logo = false
    logo_text = "REBEL FENCING"

    logo = "img/REBEL-Logo-na-stronę.jpg"
    contact_url = "/contact"

    logo_small = "img/rebel-logo-small.jpg"
    address = """<p class="text-uppercase"><strong>Rebel Fencing</strong>
        <br>Piotra Skargi 31, Wroclaw, Poland
        <br>Wrocław
        <br>50-450
        <br>
        <strong>Polska</strong>
      </p>
      """

# Enable or disable top bar with social icons
[params.topbar]
    enable = true

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = false
    tags = true
    search = true

[params.carouselTestimonials]
    items = 4
    auto_play = false
    slide_speed = 2000
    pagination_speed = 1000
    enable = false

[params.carouselHomepage]
    enable = true

[params.features]
    enable = false
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more information take a look at the README.

[params.testimonials]
    enable = false

[params.see_more]
    enable = false

[params.clients]
    enable = false

[params.recent_posts]
    enable = true

[params.footer.recent_posts]
    enable = true

[taxonomies]
    category = "categories"
    tag = "tags"
    author = "authors"
